### ISSUE TITLE
BUG: M2XClient.Device.Stream.Update() uses incorrect endpoint

### ISSUE THREAD

**Issue by azarc3** [attm2x/m2x-dot-net#12]
The M2X documentation states that updating a value for a given stream should use the endpoint  **/devices/{id}/streams/{name}/value**.

However, the path used by the M2XClient.Device.Stream.Update() method current executes a PUT request to **/devices/{id}/streams/{name}**, omitting the final necessary **/value** part of the URI. 

A successful PUT operation is possible after adding this missing last part of the URI.

**Comment by azarc3** [comment]
After further research, it's clear that the library assumes the user will know to use the .UpdateValue() method instead of the .Update() method. UpdateValue does not appear in the ATT M2X documentation and as such is not intuitive to unsuspecting users. We should consider a design change so that this type of confusion is not possible.

For now, I'm deferring development on this until further discussions with the team regarding the library design.

**Comment by fsaravia** [comment]
@azarc3 There two methods are on the M2X documentation. the `Update` method you are referring to may reference the [Create/Update Data Stream](https://m2x.att.com/developer/documentation/v2/device#Create-Update-Data-Stream) endpoint whereas the `UpdateValue` method may reference the [Update Data Stream Value](https://m2x.att.com/developer/documentation/v2/device#Update-Data-Stream-Value) endpoint. Or am I missing something?.

**Comment by azarc3** [comment]
@fsaravia Most certainly agreed. The problem is that it's not clear to the user. One is for updating the configuration of the Stream, and the other is for adding data values to the stream. While the method names make lots of sense for the REST API, they aren't necessarily intuitive to users new to the library.

Seeing that the library adheres to the M2X documentation I'm going to close this "bug".

However, I suggest that the team considering making the library method names more evident where the possibility of confusion exists. For example, those two method names would become Stream.UpdateConfiguration() and Stream.AddValue(). Little room for confusion with those. :)
