### ISSUE TITLE
BUG: Device Stream Values filtering appears to incorrectly serialize datetime values

### ISSUE THREAD

**Issue by azarc3** [attm2x/m2x-dot-net#7]
Considering the following code...

```
var device = client.Device(_testDeviceId);  // device must be accessible by Master API key
var stream = device.Stream(_testDeviceTestStreamName);   // stream must exist for device
var thresholdValue = new DateTime(2016, 5, 14, 4, 0, 0);
var valueParameters = new { start = new DateTime(2016, 5, 14, 0, 0, 0), end = new DateTime(2016, 5, 14, 4, 0, 0) };
var result = await stream.Values(valueParameters);
```

... the call to **stream.Values(valueParameters)** appears to at least incorrectly serialize datetime values; it may also incorrectly format the request overall. The API clearly supports providing these parameters (https://m2x.att.com/developer/documentation/v2/device#List-Values-from-all-Data-Streams-of-a-Device).

**Comment by mpreedom1234** [comment]
who the fuck cares? Michael F. Preedom President & Chief Executive Officer (CEO) Director-General Mgr.: Product Research & Development Innovation Design Enterprises Cobourg, Ontario Canada mikefrancispreedom@yahoo.ca 

    On Saturday, May 14, 2016 1:58 PM, Kelvin McDaniel <notifications@github.com> wrote:
 

 Considering the following code...var device = client.Device(_testDeviceId);  // device must be accessible by Master API key
var stream = device.Stream(_testDeviceTestStreamName);   // stream must exist for device
var thresholdValue = new DateTime(2016, 5, 14, 4, 0, 0);
var valueParameters = new { start = new DateTime(2016, 5, 14, 0, 0, 0), end = new DateTime(2016, 5, 14, 4, 0, 0) };
var result = await stream.Values(valueParameters);
... the call to stream.Values(valueParameters) appears to at least incorrectly serialize datetime values; it may also incorrectly format the request overall. The API clearly supports providing these parameters (https://m2x.att.com/developer/documentation/v2/device#List-Values-from-all-Data-Streams-of-a-Device).—

**Comment by azarc3** [comment]
Determined that it does work correctly but the format that must be submitted is an anonymous object with string values for the dates (it is very, very finicky):

``var tsBasis = new DateTime(2016, 5, 14, 0, 0, 0);``
``var thresholdValue = tsBasis.AddHours(4);``
``var fromValue = tsBasis.ToString("yyyy-MM-ddTHH:mm:00.000Z");``
``var toValue = thresholdValue.ToString("yyyy-MM-ddTHH:mm:59.999Z");``

``var device = client.Device(_testDeviceId);``
``var stream = device.Stream(_testDeviceTestStreamName);``
``var valueParameters = new { from = fromValue, end = toValue };``
``var result = await stream.Values(valueParameters);``
